### ISSUE TITLE
Support recent cython versions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bibi21000/python-openzwave#57]
```
Hi,

Here is a workaround for compilation issues with recent cython versions.

See also this post: 
https://groups.google.com/forum/#!topic/cython-users/1FbzEc3smLU

Best regards,

-sbi
```

Original issue reported on code.google.com by `stephane...@gmail.com` on 15 Jan 2014 at 9:11

Attachments:
* [cython19.patch](https://storage.googleapis.com/google-code-attachments/python-openzwave/issue-57/comment-0/cython19.patch)

**Comment by bibi21000** [comment]
Fixed.
Test made with cython 0.22
