### ISSUE TITLE
owsh exit on controller

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bibi21000/python-openzwave#71]
```
What steps will reproduce the problem?
1. launch ozwsh
2. cd to controller
3. the shell exit without any error message

What is the expected output? What do you see instead?

Access the controller part of the sh

What version of the python-openzwave are you using (from hg or archive)? On
what operating system or distribution? 32bits or 64 bits?

I'm using a raspberry pi with raspbian


Please provide any additional information below.


```

Original issue reported on code.google.com by `yecin...@gmail.com` on 17 Sep 2014 at 1:48

**Comment by bibi21000** [comment]
"Also in my opinion that part is not worthy enough, it should be a diferent project or removed at all"

The pyozman is for admin/developpers only. It's the best way to perform an hard reset safely. It's also the only way to get all params of a node.
