### ISSUE TITLE
this will be the official py-ozw repository?

### ISSUE THREAD

**Issue by killercode** [bibi21000/python-openzwave#92]
this will be the official py-ozw repository? I'm in doubt if it's nechry ot bibi21000? which one should I keep an eye on and send suggestions?

**Comment by bibi21000** [comment]
Hi,
This repository is the one of the original author of this library. So you can consider it as official.
You can either send notification to nechry or to me. He will surely push them to me.
I'm thinking of a new organisation for this plugin : define official puller for parts of python-openzwave : the wrapper, the api, python3, ...
nechry is interressed in the wrapper : so I prefer that you send request for the wrapper to him.
I need to make update to the api for my personal use so request must be done to me ...
But I don't know how to do it simply with github.
I'm updating the way installing, building, ... this project (to unify it with my other projet). So it must be consider in alpha state (ie make_docs is broken actually). It will be officially opened in the next few days.
HTH
bibi21000
