### ISSUE TITLE
Multiple ValueChanged Events

### ISSUE THREAD

**Issue by killercode** [bibi21000/python-openzwave#94]
Hi, i usually receive multiple value changed events, for values that were changed and something for values that didn't change...

I read something about the verified values to fix this issue. Am I correct?

What should be the correct way to solve this issue or to use the value verification?

**Comment by bibi21000** [comment]
Hi
Where did you read that ? A link should be usefull.
As you surely seen, python-openzwave uses commands from the openzwave library. Did you find something about that in their issues ?
For one device, many ? Which one ? What kind of device ? dimmer, switch ?
I've got a homepro Dimmer ZDP 230 which have strange behaviors : it send bad changed value, I need to poll it to retrieve the good one.
In the past, there were logging facilities in le lib but they have disappeared. I will reintroduce them in the 0.3.0.

**Comment by killercode** [comment]
https://groups.google.com/forum/#!searchin/openzwave/valuechanged$20verified/openzwave/iQ_kimR8RuI/ugTidspTocoJ

I am using a EHK Switchkeeper, it's a switch with some other functionalities... What I am doing now is if I receive value changed and the values is still the same (to exclude the repetitions) I ignore it

By the way can you post an example of how you poll the values, Usually it should be automatic right?

In my application I never poll values and it seems to be up to date...

**Comment by bibi21000** [comment]
Look at doc : http://bibi21000.gallet.info/index.php/en/component/sphinxdoc/documentation/3-python-openzwave-api/value.html
and examples : https://github.com/bibi21000/python-openzwave/blob/master/src-manager/pyozwman/ozwsh.py#L373

**Comment by bibi21000** [comment]
Did you find what you're looking for ?

**Comment by killercode** [comment]
Kind of,  I saw how you implemented it seems easy,  but,  I still receive a lot of duplicated values changed events.  I guess I will have to filter them my self. Also I get stock a lot of times with message Attempt.... That freezes my communication for a lot of time

**Comment by bibi21000** [comment]
Do you use the API or simply the lib ?
Maybe a poll is already defined for this device ? 
Which COMMAND_CLASS send mutiple notifications ?
