### ISSUE TITLE
which version of python-openzwave is stable 

### ISSUE THREAD

**Issue by slawekgh** [bibi21000/python-openzwave#95]
As stated in main page of the project "version (0.3.0) is under development, do not use it in production" 
So which version is stable and which procedure should I follow to install python-openzwave with quite fresh openzwave inside?

**Comment by bibi21000** [comment]
0.2.6

**Comment by bibi21000** [comment]
A new release of python-openzwave is here : 0.3.0-alpha1. Feel free to try it

**Comment by slawekgh** [comment]
great news ! thx

2015-04-08 0:09 GMT+02:00 Sébastien GALLET <notifications@github.com>:
