### ISSUE TITLE
2 problems with "Install from archive" on RaspberryPi 

### ISSUE THREAD

**Issue by slawekgh** [bibi21000/python-openzwave#96]
As stated in bibi comment: "This version (0.3.0) is under development, do not use it in a production environnement." so  I tried to find some older (more stable?) version 

I decied to follow by procedure called "Install from archive" which is described here:
http://bibi21000.gallet.info/index.php/en/component/sphinxdoc/documentation/5-python-openzwave-readme/INSTALL_ARCH.html

So below what I get: 

wget http://bibi21000.no-ip.biz/python-openzwave/python-openzwave-0.2.6.tgz
gzip -d python-openzwave-0.2.6.tgz
tar xvf python-openzwave-0.2.6.tar
cd python-openzwave-0.2.6/
cat VERSIONS 
OPZW=r749
PYOZW=0.2.6

cat openzwave/openzwave.spec | head -20 | grep Version
Version: 1.0.730

then I run: 
./compile.sh

[...]
Building Msg.o
Creating /home/pi/test/python-openzwave-0.2.6/openzwave/cpp/src/vers.cpp file
Building vers.o
/home/pi/test/python-openzwave-0.2.6/openzwave/cpp/src/vers.cpp:4:30: error: expected primary-expression before ‘;’ token
/home/pi/test/python-openzwave-0.2.6/openzwave/cpp/build/support.mk:93: recipe for target '/home/pi/test/python-openzwave-0.2.6/openzwave/cpp/build/.lib/vers.o' failed
make: *** [/home/pi/test/python-openzwave-0.2.6/openzwave/cpp/build/.lib/vers.o] Error 1

here is file vers.cpp :
#include "Defs.h"
uint16_t ozw_vers_major = 1;
uint16_t ozw_vers_minor = 0;
uint16_t ozw_vers_revision = ;

so I put 730 in last line:
uint16_t ozw_vers_revision = 730;

and then run compile.sh again , so it jumped across previous error and went forward

Next it stopped at:

 ./compile.sh 
[...]

running build_ext
skipping 'lib/libopenzwave.cpp' Cython extension (up-to-date)
building 'libopenzwave' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iopenzwave/cpp/src -Iopenzwave/cpp/src/value_classes -Iopenzwave/cpp/src/platform -Iopenzwave/cpp/build/linux -I/usr/include/python2.7 -c lib/libopenzwave.cpp -o build/temp.linux-armv6l-2.7/lib/libopenzwave.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-armv6l-2.7/lib/libopenzwave.o openzwave/libopenzwave.a -ludev -lstdc++ -o build/lib.linux-armv6l-2.7/libopenzwave.so
g++: error: openzwave/libopenzwave.a: No such file or directory
error: command 'g++' failed with exit status 1

Of course cython is in 0.22 version

**Comment by bibi21000** [comment]
Of course cython is in 0.22 version : that's the problem. Python-openzwave 0.2.6 require cython 0.14.
Follow instructions in INSTALL_ARCH.txt from the archive.

**Comment by slawekgh** [comment]
I have downgraded cython and make everything one again from the fresh tarball  

pi@raspberrypi ~ $ cython -V
Cython version 0.14


pi@raspberrypi ~/python-openzwave-0.2.6 $ ./compile.sh 
-----------------------------------------------------------------
|   Build openzwave                                             |
-----------------------------------------------------------------
Building vers.o
Linking Static Library
Linking Shared Library
-----------------------------------------------------------------
|   Build python-openzwave                                      |
-----------------------------------------------------------------
running build
running build_py
package init file 'lib/__init__.py' not found (or not a regular file)
package init file 'lib/__init__.py' not found (or not a regular file)
running build_ext
cythoning lib/libopenzwave.pyx to lib/libopenzwave.cpp
building 'libopenzwave' extension
creating build
creating build/temp.linux-armv6l-2.7
creating build/temp.linux-armv6l-2.7/lib
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iopenzwave/cpp/src -Iopenzwave/cpp/src/value_classes -Iopenzwave/cpp/src/platform -Iopenzwave/cpp/build/linux -I/usr/include/python2.7 -c lib/libopenzwave.cpp -o build/temp.linux-armv6l-2.7/lib/libopenzwave.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
creating build/lib.linux-armv6l-2.7
g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-armv6l-2.7/lib/libopenzwave.o openzwave/libopenzwave.a -ludev -lstdc++ -o build/lib.linux-armv6l-2.7/libopenzwave.so
g++: error: openzwave/libopenzwave.a: No such file or directory
error: command 'g++' failed with exit status 1

**Comment by bibi21000** [comment]
g++: error: openzwave/libopenzwave.a: No such file or directory

There is a problem compiling the openzwave c++ library (the part in the ...)

**Comment by slawekgh** [comment]
so as I understand Your comment my case is not pythonopenzwave related but related only to OZW ?
 if answer=Yes sorry for opening ticket and I will move it to OZW forum

**Comment by slawekgh** [comment]
Just one more question - is there any chance that python-openzwave will have some new version of OZW inside the archive ? Today there is 1.2.730 and in PZW is 1.0.730

**Comment by bibi21000** [comment]
so as I understand - my case is not pythonopenzwave related but related only to OZW ?
I don't know ... without log it's impossible to say

Just one more question - is there any chance that python-openzwave will have some new version of OZW inside the archive ?
Yes when 0.3.0 will be ok
