### ISSUE TITLE
Updating capabilities of a node

### ISSUE THREAD

**Issue by DirtySecret** [bibi21000/python-openzwave#99]
Hello,

I am wondering if there is a way to update the capabilities of a node. Sometimes when I change the source of power from USB to batteries, the capabilities are still "Listening, Routing, etc..." so it still assumes that my device is USB Powered.

How can I update that value ? "node.refresh_info()" didn't work

Thanks in advance

**Comment by bibi21000** [comment]
Hello,
Don't know how to resolve your problem. Did you try to "heal" the node ?
Maybe the openzwave group can help you
Hope this help
